# Exposure Cohort Definitions

```{r base-cohort, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
allCohorts <- read.csv(system.file("cohorts", "cohortDefinition.csv", package = "LegendHtnStepCare"))
baseCohortJson <- allCohorts %>% filter(cohortId == 1000001)
baseCohort <- RJSONIO::fromJSON(baseCohortJson$json)
baseCohortJson <- RJSONIO::toJSON(baseCohort, digits = 50)

LegendHtnStepCare:::printCohortDefinitionFromNameAndJson(name = "Class-vs-Class Exposure (ACEI after Thiazide) Cohort / OT1 {#class-cohort}", json = baseCohortJson)
```

## Heterogenity Study Inclusion Criteria {#atlas-subgroups}
### Younger age subgroup
```{r heterogenity-cohort1, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
youngerJson <- allCohorts %>% filter(cohortId == 1100001)
youngerCohort <- CirceR::cohortExpressionFromJson(youngerJson$json)
printPrimaryCriteria(youngerCohort)
```

### Middle age subgroup
```{r heterogenity-cohort2, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
middleJson <- allCohorts %>% filter(cohortId == 1200001)
middleCohort <- CirceR::cohortExpressionFromJson(middleJson$json)
printPrimaryCriteria(middleCohort)
```

### Older age subgroup
```{r heterogenity-cohort3, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
olderJson <- allCohorts %>% filter(cohortId == 1300001)
olderCohort <- CirceR::cohortExpressionFromJson(olderJson$json)
printPrimaryCriteria(olderCohort)
```

### Female subgroup
```{r heterogenity-cohort4, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
# Sex
femaleJson <- allCohorts %>% filter(cohortId == 1500001)
femaleCohort <- CirceR::cohortExpressionFromJson(femaleJson$json)
printPrimaryCriteria(femaleCohort)
```

### Male subgroup
```{r heterogenity-cohort5, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
maleJson <- allCohorts %>% filter(cohortId == 1400001)
maleCohort <- CirceR::cohortExpressionFromJson(maleJson$json)
printPrimaryCriteria(maleCohort)
```


### Black or African American subgroup
```{r heterogenity-cohort-race, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
# Race
removeInclusionRules <- function(json) {
  obj <- RJSONIO::fromJSON(json)
  obj$InclusionRules[[1]] <- NULL # delete 1
  obj$InclusionRules[[1]] <- NULL # delete 2
  obj$InclusionRules[[1]] <- NULL # delete 3
  obj$InclusionRules[[1]] <- NULL # delete 3
  obj$InclusionRules[[1]] <- NULL # delete 3
  RJSONIO::toJSON(obj, digits = 50)
}

blackJson <- allCohorts %>% filter(cohortId == 1700001)
blackCohort <- CirceR::cohortExpressionFromJson(removeInclusionRules(blackJson$json))
printInclusionCriteria(blackCohort)
```

# Outcome Cohort Definitions

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
invisible(readr::read_csv(system.file("settings/OutcomesOfInterest.csv", package = "LegendHtnStepCare")) %>%
  mutate(text = atlasName, fileName = name) %>%
  select(text, fileName) %>%
  rowwise() %>%
  mutate(
    output = printCohortDefinition(
      list(name = text,
           jsonFileName = system.file("cohorts", paste0(fileName, ".json"), package = "LegendHtnStepCare")
      )
    )))
```

# Negative Control Concepts {#negative-controls}

\captionsetup{labelformat=empty}

```{r, echo=FALSE, warning=FALSE, message=FALSE}
negative_controls <- readr::read_csv(system.file("settings/NegativeControls.csv", package = "LegendHtnStepCare")) %>%
  select(name, conceptId) %>% arrange(name)

colnames(negative_controls) <- c("", "Concept ID")

tab <- kable(negative_controls, booktabs = TRUE, linesep = "", longtable = TRUE,
      caption = "Negative outcome controls specified through condition occurrences that map to (a descendent of) the indicated concept ID") %>%
  kable_styling(bootstrap_options = "striped", latex_options = "striped")

if (knitr::is_latex_output()) {
  tab %>%
    column_spec(1, width = "40em") %>%
    column_spec(2, width = "15em") %>%
    kable_styling(font_size = latex_table_font_size,
                  latex_options = c("repeat_header"),
                  repeat_header_continued = "\\textit{(Continued on Next Page...)}")

} else {
  tab
}
```